#!/bin/bash

## Usage: process_dicoms rawdir dir

## look for MRF dicoms

shopt -s nocasematch

rawdir=$1
dir=$2
mkdir -p ${dir}/MRF_images
wd=${dir}/MRF_images

cd $wd

for subj in $( ls $rawdir | sort -V ); do
	mkdir -p ${subj}
	i=1
	for file in $( ls ${rawdir}/${subj} | sort -V ); do
		if [[ $file =~ .*"mrf".* ]] && [[ $file =~ .*"t1".* ]] && [[ ! $file =~ .*"masked".* ]]; then ## T1 map
			mrconvert $file ${subj}/T1_temp_map_${i}.nii -nthreads 0 -force
			i=$((i+1))
			continue
		
		elif [[ $file =~ .*"mrf".* ]] && [[ $file =~ .*"t1".* ]] && [[ $file =~ .*"offset".* ]] && [[ ! $file =~ .*"masked".* ]]; then ## T1 map offset
			mrconvert $file ${subj}/T1_temp_map_${i}.nii -nthreads 0 -force
			i=$((i+1))
			continue
		
		fi
	done

	## check if offset
	if [[ ! -f T1_temp_map_3.nii ]]; then
		mrcat ${subj}/T1_temp_map_2.nii ${subj}/T1_temp_map_1.nii ${subj}/T1_temp_1.nii -nthreads 0 -force

	else

		mrcat ${subj}/T1_temp_map_2.nii ${subj}/T1_temp_map_1.nii ${subj}/T1_temp_1.nii -nthreads 0 -force

		mrcat ${subj}/T1_temp_map_4.nii ${subj}/T1_temp_map_3.nii ${subj}/T1_temp_2.nii -nthreads 0 -force

		fslmaths ${subj}/T1_temp_1.nii -add ${subj}/T1_temp_2.nii ${subj}/T1_map.nii
	fi
	rm -rf *temp*

done

			
	
