#!/usr/bin/bash

subj=$1
WORKDIR=$2
imageref=$3 #make sure ref is T2w_acpc.nii.gz if T1 map, T1w_acpc.nii.gz if T2 map

SUBJECTS_DIR=${WORKDIR}/FS
mkdir -p ${SUBJECTS_DIR}

export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$ncpus

rsync -vaz ${imageref} .

recon-all -autorecon1 -i T1_map.nii -noskullstrip -subjid $subj -sd $SUBJECTS_DIR

mrconvert T1.mgz T1.nii -nthreads $ncpus -force

antsRegistration --verbose 1 --dimensionality 3 --float 0 --collapse-output-transforms 1 --output [MRFinref,MRFinrefRigid.nii.gz,MRFinrefInverseRigid.nii.gz] --interpolation Linear --use-histogram-matching 0 --winsorize-image-intensities [0.005,0.995] --initial-moving-transform [${imageref},T1.nii,1] --transform Rigid[0.1] --metric MI[${imageref},T1.nii,1,32,Regular,0.25] --convergence [1000x500x250x100,1e-6,10] --shrink-factors 8x4x2x1 --smoothing-sigmas 3x2x1x0vox

bet2 ${imageref} dummy -m -f 0.0

rm dummy.nii.gz

fslmaths MRFinrefRigid.nii.gz -mul dummy_mask.nii.gz brainmask.nii

mrconvert brainmask.nii brainmask.mgz -nthreads $ncpus -force

recon-all -autorecon2 -autorecon3 -normneck -subjid $subj -sd ${SUBJECTS_DIR} -no-isrunning
